Packaging
herbie/aws-sns-sqs-adapter pull request #1
Opened 2020-07-17 08:45 UTC by ruimbribeiro

2020-07-24 08:05 UTC, tobi812 requested changes
Just found a couple of minor things, besides that it looks supernice :+1:

2020-07-24 08:05 UTC, tobi812 commented on example_consumer/docker-compose-sqs-consumer.yml
> +
We could think about adding an sqs/sns container here for testing.

2020-07-24 08:05 UTC, tobi812 commented on aws_sns_sqs_adapter/django_settings.py
> +AWS_SQS_SNS_ENDPOINT_URL = env.str('AWS_SQS_SNS_ENDPOINT_URL', " ")
Let's stick to single quotes here.

2020-07-24 08:05 UTC, tobi812 commented on aws_sns_sqs_adapter/django_settings.py
> +print(INSTALLED_APPS)
Do we need this line here?

2020-07-31 11:41 UTC, tobi812 commented on aws_sns_sqs_adapter/publisher/aws_sns_topic_publisher.py
> +        # Topics are immutable to it's safe to call create as the already existing topic will be returned
:+1:

2020-07-31 11:42 UTC, tobi812 approved these changes
LGTM, nice job :+1:

2020-08-12 12:49 UTC, ruimbribeiro commented on example_consumer/docker-compose-sqs-consumer.yml
> +
The idea was that this container would be in the sandbox docker-compose as we need to publish things from there, that's why I added the sandbox docker network here as an _external one_ 

```
networks:
  sandbox_herbie-network:
    external: true
```

2020-08-12 15:21 UTC, tobi812 commented on example_consumer/docker-compose-sqs-consumer.yml
> +
aha makes sense :+1:

2020-08-12 15:22 UTC, tobi812 approved these changes
Wonderful: LGTM :+1:

2020-08-13 07:23 UTC, merged